server:
  port: 8084
spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          # uri: file:///${user.home}/config-repo
          uri: https://github.com/ppsang/SpringcloudConfig
          searchPaths: respo
          label: master
          # searchPaths: '{application}'  #搜索各个以服务名命名的文件夹下的所有yml
          # 支持label(分支名称) username(访问git仓库的用户名) password(访问git仓库的用户密码)
eureka:
  instance:
    hostname: localhost
    instance-id: localhost:8084
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/  #注册中心地址